services:
  - type: web
    name: auth-project
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn auth_project.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        sync: false          # set manually in Render dashboard
      - key: DATABASE_URL
        sync: false          # set manually in Render dashboard
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false